"""empty message

Revision ID: 443c278eeef8
Revises: e85a4e34dce5
Create Date: 2021-04-25 09:10:05.880523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443c278eeef8'
down_revision = 'e85a4e34dce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullName', sa.String(length=255), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'fullName')
    # ### end Alembic commands ###
