"""empty message

Revision ID: 7332729ff8bf
Revises: 8447fee956fc
Create Date: 2021-04-26 11:06:51.791264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7332729ff8bf'
down_revision = '8447fee956fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'car_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cars', 'colour',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('cars', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=400),
               existing_nullable=True)
    op.alter_column('cars', 'make',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cars', 'model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('cars', 'photo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('cars', 'transmission',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'biography',
               existing_type=sa.VARCHAR(length=2500),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
    op.alter_column('users', 'biography',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=2500),
               existing_nullable=True)
    op.alter_column('cars', 'transmission',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('cars', 'photo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('cars', 'model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('cars', 'make',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('cars', 'description',
               existing_type=sa.String(length=400),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('cars', 'colour',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('cars', 'car_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
