"""empty message

Revision ID: c2b93ea7eff7
Revises: 3082eb3f1ba9
Create Date: 2021-04-19 03:51:10.508966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b93ea7eff7'
down_revision = '3082eb3f1ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('description', sa.String(length=20000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'description')
    # ### end Alembic commands ###
